name: Build

on:
  push:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]
  pull_request:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & install libnds fork
        run: |
          git clone https://codeberg.org/trustytrojan/libnds --branch canonical-mode --depth 1
          cd libnds
          git clone https://codeberg.org/blocksds/wf-fatfs --depth 1 fatfs
          make install -j

      - name: Install Autotools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends autoconf automake libtool

      - name: Build nds-dash
        run: |
          cd ..
          git clone https://github.com/trustytrojan/nds-dash --depth 1
          cd nds-dash
          ./configure.sh
          make -j
          cp src/libdash.a .

      - name: Install CMake
        run: |
          which cmake && exit 0
          apt-get update
          apt-get install -y --no-install-recommends cmake
          which cmake

      - name: Configure CMake
        run: cmake --preset blocksds-release

      - name: Build project
        run: cmake --build build -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndsx-with-programs
          if-no-files-found: error
          path: |
            ./build/*.nds
            ./build/*.dsl
