name: Build

on:
  push:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]
  pull_request:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone libnds fork
        id: clone-libnds-fork
        run: |
          git clone https://codeberg.org/trustytrojan/libnds --branch canonical-mode --depth 1
          echo "commit_hash=$(cd libnds; git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Cache libnds fork
        id: cache-libnds-fork
        uses: actions/cache@v5
        with:
          path: ${{ env.BLOCKSDS }}/libs/libnds/lib/libnds*.a
          key: libnds-${{ steps.clone-libnds-fork.outputs.commit_hash }}

      - name: Build & install libnds fork
        if: steps.cache-libnds-fork.outputs.cache-hit != 'true'
        run: |
          cd libnds
          git clone https://codeberg.org/blocksds/wf-fatfs --depth 1 fatfs
          make install -j INSTALLDIR=$BLOCKSDS/libs/libnds

      - name: Clone Busybox
        id: clone-busybox
        run: |
          git clone https://github.com/trustytrojan/busybox ../busybox --depth 1
          echo "commit_hash=$(cd ../busybox; git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      
      - name: Cache Busybox
        id: cache-busybox
        uses: actions/cache@v5
        with:
          path: ../busybox/libbusybox.a
          key: busybox-${{ steps.clone-busybox.outputs.commit_hash }}

      - name: Install necessary packages to build Busybox
        if: steps.cache-busybox.outputs.cache-hit != 'true'
        run: apt update && apt install -y --no-install-recommends build-essential file

      # Might want to comment them out instead so that they can be restored after Busybox is built
      - name: Delete `itoa` and `utoa` declarations in `stdlib.h`
        if: steps.cache-busybox.outputs.cache-hit != 'true'
        run: sed -i -E '/^char \*[iu]toa\(.+__picolibc_export;$/d' /opt/wonderful/toolchain/gcc-arm-none-eabi/arm-none-eabi/include/stdlib.h

      - name: Build Busybox
        if: steps.cache-busybox.outputs.cache-hit != 'true'
        run: cd ../busybox && bash build.sh

      - name: Install CMake
        run: apt update && apt install -y --no-install-recommends cmake

      - name: Configure CMake
        run: cmake --preset blocksds-release

      - name: Build project
        run: cmake --build build -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndsx-with-programs
          if-no-files-found: error
          path: |
            ./build/*.nds
            ./build/*.dsl
